# Dockerfile.root   
FROM python:3.12-slim

WORKDIR /app

# Copy necessary files and folders
COPY start_api.py .
COPY common ./common
COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .
COPY data ./data
COPY ai ./ai

RUN apt-get update && \
    apt-get install -y git libpq-dev gcc build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN pip install uv
RUN uv sync
ENV PYTHONPATH=/app/.venv/lib/python3.12/site-packages
CMD ["python", "start_api.py"]
