#  Dockerfile.data      
FROM python:3.12-slim
WORKDIR /app
ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}
# Copy necessary files and folders
COPY data/${SERVICE_NAME}.py .
COPY data ./data
COPY common ./common
COPY ai ./ai
COPY start_consumers.py . 
COPY requirements.txt .
RUN apt-get update && \
    apt-get install -y git libpq-dev gcc build-essential && \
    rm -rf /var/lib/apt/lists/*
RUN pip install uv
RUN uv sync
CMD ["sh", "-c", "python /app/${SERVICE_NAME}.py"]
