#  Dockerfile.data      
FROM python:3.12-slim
WORKDIR /app
# Copy necessary files and folders
RUN apt-get update && \
    apt-get install -y git libpq-dev gcc build-essential && pip install uv && \
    rm -rf /var/lib/apt/lists/*
COPY data ./data
COPY common ./common
COPY ai ./ai
COPY start_consumers.py .
COPY run_migrations.py .
COPY pyproject.toml .
COPY uv.lock .
RUN uv sync
