# Dockerfile.root
FROM python:3.9-slim

WORKDIR /app

# Copy necessary files and folders
COPY start_api.py .
COPY common ./common
COPY app ./app
COPY requirements.txt .

RUN pip install psycopg2-binary && pip install --no-cache-dir -r requirements.txt

CMD ["python", "start_api.py"]
