name: Merge Feature Branch into Main

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  merge-to-main:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0  # Fetch all history for the refs

      - name: Fetch feature branch
        run: git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}

      - name: Merge feature branch into main
        run: |
          git checkout main
          git merge ${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into main"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin main
