name: Auto-merge feature to main

on:
  push:
    branches:
      - 'feature/**'  # Trigger on push to any feature branch
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Auto-merge feature to main"]
    types:
      - completed
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Merge feature branch to main
        run: |
          git checkout main
          git merge ${{ github.ref }}
          git push origin main
