name: TBD and Docker Build

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  version-bump:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine version increment
        id: determine_increment
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == *"[major]"* ]]; then
            echo "INCREMENT=major" >> $GITHUB_OUTPUT
          elif [[ $commit_message == *"[minor]"* ]]; then
            echo "INCREMENT=minor" >> $GITHUB_OUTPUT
          else
            echo "INCREMENT=patch" >> $GITHUB_OUTPUT
          fi

      - name: Increment version
        id: increment_version
        run: |
          version=$(grep -m1 version pyproject.toml | cut -d '"' -f2)
          IFS='.' read -ra ver <<< "$version"
          major=${ver[0]}
          minor=${ver[1]}
          patch=${ver[2]}
          increment_type="${{ steps.determine_increment.outputs.INCREMENT }}"
          if [[ "$increment_type" == "major" ]]; then
            major=$((major + 1))
            minor=0
            patch=0
          elif [[ "$increment_type" == "minor" ]]; then
            minor=$((minor + 1))
            patch=0
          else
            patch=$((patch + 1))
          fi
          new_version="$major.$minor.$patch"
          sed -i "s/version = \"$version\"/version = \"$new_version\"/" pyproject.toml
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pyproject.toml
          git commit -m "Bump version to ${{ steps.increment_version.outputs.VERSION }}"
          git push

  merge-to-main:
    needs: version-bump
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Merge feature branch into main
        run: |
          git fetch origin ${{ github.ref }}
          git merge --no-ff ${{ github.ref }} -m "Merge ${{ github.ref }} into main"
          git push

  build-and-push:
    needs: merge-to-main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          version=$(grep -m1 version pyproject.toml | cut -d '"' -f2)
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Build and push start_api
        run: |
          docker build -f Dockerfile.root -t ${{ secrets.ACR_LOGIN_SERVER }}/start_api:${{ steps.get_version.outputs.VERSION }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/start_api:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push data services
        run: |
          services=("emails_manager" "hunter_domain_finder" "meetings_consumer" "pdl" "person_langsmith" "persons_manager")
          for service in "${services[@]}"
          do
            docker build -f Dockerfile.data --build-arg SERVICE_NAME=$service -t ${{ secrets.ACR_LOGIN_SERVER }}/$service:${{ steps.get_version.outputs.VERSION }} .
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/$service:${{ steps.get_version.outputs.VERSION }}
          done
