name: UV-Test

on:
  push:
    branches:
      - 'uv-**'  # Trigger on push to any feature branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install `uv`
      run: pip install uv

    - name: Install dependencies
      run: uv sync


